# first useful Makefile

# Define the C compiler to use
CC = gcc

# Define the c flags compiler
CFLAGS = -g -Wall -Wextra -Werror -pedantic

0-hreadelf: 0_main.c
	$(CC) $(CFLAGS) 0_main.c -o 0-hreadelf
	touch 0_main.c
